/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContestedAreaSelector: typeof import('./src/components/ContestedAreaSelector.vue')['default']
    GoogleMap: typeof import('./src/components/GoogleMap.vue')['default']
    GoogleMapSession: typeof import('./src/components/GoogleMapSession.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MapComparator: typeof import('./src/components/MapComparator.vue')['default']
    OsmMap: typeof import('./src/components/OsmMap.vue')['default']
    RegionSelector: typeof import('./src/components/RegionSelector.vue')['default']
  }
}
